### ISSUE TITLE
Games where 2-player mode and sometimes border doesn't work

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/SGB_MiSTer#2]
Thanks so much for this core again. I grew up with a Super Game Boy as my primary way to play the Game Boy library so it's special to me. You also helped so much with the borders and other stuff on the Game Boy core and it's greatly appreciated.

Here's a list of some games where the 2-player mode doesn't seem to work. The title screen shows the option but it gives some kind of error beep when you try to select it. Also in some of these there is an odd correlation between the 2p not working and the border not working. I'm listing off the Japanese versions, but their US/EU counterparts do the same thing when I tested them.

* Gekitou Power Modeller (Japan) - No 2-player.
* ~~Nettou Toshinden (Japan) - No 2-player, no border.~~
* ~~Nettou Real Bout Garou Densetsu Special (Japan) - No 2-player, no border.~~
* ~~Nettou The King of Fighters '96 (Japan) - No 2-player, no border.~~
* ~~Nettou World Heroes 2 Jet (Japan) - No 2-player, no border.~~
* Tetris DX - No 2-player, ~~no borders.~~

I'm sure there are many more so no need to go into a list of all of them since maybe fixing one or two of these would clear most of them up.

**Comment by paulb-nl** [comment]
Tetris DX didn't work properly because the SGB boot rom was too fast compared to the original boot rom. I have added a delay to fix that and it is also now possible to load the original boot roms in the menu. Tetris DX will show different borders between the original SGB1&2 boot roms.

The other games most likely had the same issue.

**Comment by miller2b** [comment]
Hello, thanks for updating this core and fixing the border issues. Unfortunately, it seems it was only the borders that were fixed and the 2-player modes of the games birdybro listed are still inaccessible.

**Comment by birdybro** [comment]
I updated the top post to strikethrough the fixed issues, thanks for retesting! Looks like the SNK games relied heavily on whatever that timing change fixed! :)

**Comment by paulb-nl** [comment]
The Tetris DX manual doesn't mention 2 player support on SGB. It says you need to use a link cable so I think 2p can only work if you use SNAC.

I'm guessing it is the same thing with Gekitou Power Modeller.

**Comment by miller2b** [comment]
> 

I can confirm that Gekitou has SGB 2P capability as friend has the game on real hardware, as seen in this picture:
https://cdn.discordapp.com/attachments/935305899323568159/953454395054518302/20220315_204700.jpg

**Comment by paulb-nl** [comment]
It appears that you need to unlock 2P somehow. Anyway, it can be unlocked by pressing UU RR DD LL on the Capcom logo. You will hear a chime if done correctly. This will be saved to cart ram so it only needs to be done once.

https://gamefaqs.gamespot.com/gameboy/997541-gekitou-power-modeler/cheats

**Comment by miller2b** [comment]
Haha awesome, that did the trick! Turns out I got super mixed up by a friend saying "it just works" when in reality he had a used copy so the code was already applied. Thanks again for all your hard work!
