### ISSUE TITLE
Wario Blast featuring Bomberman / Bomberman GB (Japan): wrong behavior

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/SGB_MiSTer#4]
Wario Blast Featuring Bomberman! (USA, Europe) (SGB Enhanced).gb
CRC32: 927B57A1
Bomberman GB (Japan) (SGB Enhanced).gb
CRC32: 94337D56
(Not to be confused with the game called Bomberman GB internationally. The Japanese Bomberman GB and Wario Blast are the same game).

This game displays wrong behavior on SGB core. The game is supposed to have a custom border and color palette. On MiSTer core it does not load custom border and the colors are completely wrong.

![20220720_035733-Wario Blast Featuring Bomberman! (USA, Europe) (SGB Enhanced)](https://user-images.githubusercontent.com/70150033/179874724-dec37ca5-c161-47cf-abc7-26daaf9e49e1.png)
![20220720_035718-Bomberman GB (Japan) (SGB Enhanced)](https://user-images.githubusercontent.com/70150033/179874746-62fbc3cb-d1aa-4e28-a0a3-61ccdaba338e.png)

For reference, here are emulated screenshots from ares v129:
![Super Game Boy 2 (Japan) 2022-07-20 04-19-37](https://user-images.githubusercontent.com/70150033/179875068-3e6921fd-a21d-4a36-aa18-239a4b6afc9b.png)
![Super Game Boy 2 (Japan) 2022-07-20 04-19-17](https://user-images.githubusercontent.com/70150033/179875081-256a07eb-2a02-4351-bc93-65e5215f6f45.png)

**Comment by paulb-nl** [comment]
This is likely the same issue as #2

**Comment by Thelypody** [comment]
Solved in the latest release. Thanks!
