### ISSUE TITLE
SNES controller mostly doesn’t work when Serial SNAC GB enabled

### ISSUE THREAD

**Issue by RaspberryAlpine** [MiSTer-devel/SGB_MiSTer#5]
MiSTer v221124
OS v220413

SGB_221012.rbf

SBG2 bios
SGB2.boot

SGB Speed: SGB2

Description of the issue 

When I enable SNAC GB the USB controller for the most part stops working. The dpad, A, B, Y, Start, and Select become unresponsive. Some buttons continue to work: X, L, and R. If enter the the Super Gameboy’s bios menu with L+R, then the rest of the buttons work but only in the Super Gameboy bios menu. 

The SNAC GB link cable itself works. With a linked gameboy I was able to start a 2 player Tetris game.

**Comment by paulb-nl** [comment]
I think it incorrectly swaps controller 1 & 2 when SNAC GB is enabled. Try to set Swap joysticks to Yes. That should switch it back.

**Comment by RaspberryAlpine** [comment]
Swap Joysticks: Yes 
Has no effect.

However using a second USB controller does work.

**Comment by paulb-nl** [comment]
This is fixed in release 20230226 by d09b3169740d723da6e3de6a70c19dfa24fb0a89
